spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.52:3306/auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  session:
    timeout: 12h

mybatis-plus:
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    aggressiveLazyLoading: true
    # 如需要打印sql日志则放开下条配置
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    enabled: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true

# Swagger 文档配置
swagger:
  title: "Springboot 3"
  description: "Springboot 3.X Demo"
  license: "Apache 2.0"
  license-url: "http://www.apache.org/licenses/LICENSE-2.0"
  version: "1.0"
  contact:
    name: "中船（浙江）海洋科技 软件开发中心"
    url: "http://www.csscocean.com"